### ISSUE TITLE
[Bug]:  VIRUS detect

### ISSUE THREAD

**Issue by MrTokyo12345** [spartacus04/jext-reborn#315] opened 2024-04-22 20:41 UTC
### Describe the bug

![image](https://github.com/spartacus04/jext-reborn/assets/57362525/35670ebb-bfb7-42ae-9eb9-c1eba7eeb828)

### Steps to reproduce

download on window2s 11

### Expected behaviour

virus detect

### Server Version

1.20.4

### Server Type

Spigot

### Jukebox Behaviour

Vanilla

### Before submitting the issue

- [X] I have searched the issue tracker and did not find an issue describing my bug.
- [X] I agree to the fact that if this issue becomes inactive it will be closed.
- [X] I agree to the fact that if most fields in this issue are not filled correctly the issue will be marked as invalid and closed.

**Comment by spartacus04** [comment] 2024-04-23 04:04
Duplicate of #297

**Closed** 2024-04-23 04:05 UTC
Labels: bug
